name: QA Run 23f1002137@ds.study.iitm.ac.in

on:
  push:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run Script
        run: python scrape.py
